{% set name = "meds" %}
{% set version = "0.9.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/meds/archive/v{{ version }}.tar.gz
  sha256: 0d8a82d89cfb791d777c5404696fdf48368eb566a54bddc7c36b7dbadb5178e0

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - numpy
  run:
    - python
    - fitsio
    - pyyaml
    - esutil
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - meds

about:
  home: https://github.com/esheldon/meds
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python and C libraries to work with Multi Epoch Data Structures
  doc_url: https://github.com/esheldon/meds
  dev_url: https://github.com/esheldon/meds

extra:
  recipe-maintainers:
    - beckermr
    - esheldon
