{% set name = "meds" %}
{% set version = "0.9.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/meds/archive/v{{ version }}.tar.gz
  sha256: 2f469e554bec6100f8ca3298c18f4c69c8198006c00cd57ae03cd55d4951961c

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - fitsio
    - pyyaml
    - esutil
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - meds

about:
  home: https://github.com/esheldon/meds
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python and C libraries to work with Multi Epoch Data Structures
  doc_url: https://github.com/esheldon/meds
  dev_url: https://github.com/esheldon/meds

extra:
  recipe-maintainers:
    - beckermr
    - esheldon
