{% set name = "meds" %}
{% set version = "0.9.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/meds/archive/v{{ version }}.tar.gz
  sha256: 465e646ca1301dca6b051c8ce5ccdd0edb266453e7dc5221930c52d742034b0b

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - fitsio
    - pyyaml
    - esutil
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - meds

about:
  home: https://github.com/esheldon/meds
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python and C libraries to work with Multi Epoch Data Structures
  doc_url: https://github.com/esheldon/meds
  dev_url: https://github.com/esheldon/meds

extra:
  recipe-maintainers:
    - beckermr
    - esheldon
